//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Rating_Id { get; set; }
        public int Product_Id { get; set; }
        public int User_id { get; set; }
        public int Value { get; set; }
        public string Comment { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
