export const SEARCH_PRODUCTS_USERS_ACTION = "SEARCH_PRODUCTS_USERS_ACTION";
export const GET_PRODUCT_ACTION = "GET_PRODUCT_ACTION";
export const GET_RECOMMENDED_ACTION = "GET_RECOMMENDED_ACTION";
export const RATE_PRODUCT_ACTION = "RATE_PRODUCT_ACTION";